# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

### Export once
(type include > /dev/null 2>&1) && EXP=0 || EXP=1

if [ "$EXP" -eq 1 ]; then

    function include() {
	for i in "$@"; do
	    local file="" tfile="${i%% *}" tparam="${i#* }"
	    [ "$tfile" == "$tparam" ] && tparam=''
            [ -f "$VLIBS/lib.$tfile" ] && tfile="$VLIBS/lib.$tfile";
            if [ -f "$tfile"  ]; then
                [[ "$VINCS" =~ "$tfile:"  ]] || {
                    set ""
                    source $tfile $tparam
                    VINCS="$VINCS$file:"; }
            fi
	    # [ -f "$VLIBS/lib.$tfile" ] && file="$VLIBS/lib.$tfile $tparam"
	    # [ -f "$tfile" ] && file="$tfile $tparam"
	    # [ -n "$file" ] && [[ "$VINCS" =~ "$file:" ]] || { source $file; VINCS="$VINCS$file:"; }
	done
    }

    if [ -n "$ZSH" ]; then
	HOSTNAME="$HOST"
	export ZSH_EXPORTED_FUNCTIONS="$(functions include)"
    else
	export -f include
    fi

    export VDOT="$HOME/.local/vdot"
    export VTMP="$HOME/.local/tmp"
    export VTOOLS="$HOME/.local/tools"
    export VBIN="$HOME/.bin"
    export VLIBS="$VBIN/lib"
    export VINIS="$VBIN/ini"
    export VHOSTID="$USER@$HOSTNAME"
    export VACCOUNT="$VBIN/account"
    export VUSER="$VACCOUNT/$VHOSTID"
    export VGL_DATA="$VBIN/data"
    export VUSER_DATA="$VUSER/data"
    export VBESUDO="$($VLIBS/lib.misc check_sudo)"
fi

if [ "$EXP" -eq 1 ]; then
# export EDITOR="$(which vim)"

# history #
export HISTTIMEFORMAT="%m-%d %H:%M "
export PROMPT_COMMAND="history -a" # 实时追加history，不必等用户退出才将内存中的history记录到文件
VTTY="$(tty)"
export HISTFILE=$VTMP/.bash_history_"${VTTY##*/}"
unset VTTY

# don't put duplicate lines or lines starting with space in the history.
# export HISTCONTROL=ignoreboth
# export HISTCONTROL=erasedups       # 使用HISTCONTROL清除整个命令历史中的重复条目
export HISTCONTROL=ignoredups:erasedups
# export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

export HISTSIZE=1000      # 定义了 history 命令输出的记录数.
export HISTFILESIZE=10000 # 定义了在 .bash_history 中保存命令的记录总数.

# export HISTFILE=/data1/home/wgao/.local/history/$(date +%m%d).log
export LESSHISTFILE=$VTMP/.lesshst

# Where user-specific configurations should be written (analogous to /etc).
# Should default to $HOME/.config.
# export XDG_CONFIG_HOME=$HOME/.local/config

# Where user-specific non-essential (cached) data should be written (analogous to /var/cache).
# Should default to $HOME/.cache.
# export XDG_CACHE_HOME=$VTMP/.cache

# Where user-specific data files should be written (analogous to /usr/share).
# Should default to $HOME/.local/share.
export XDG_DATA_HOME=$HOME/.local/share

# export FONTCONFIG_FILE="$XDG_CONFIG_HOME/fontconfig/fonts.conf"

# export LC_ALL=en_US.UTF-8
# export LANG=en_US.utf8
# export LANG=zh_CN.UTF-8
# export TMUX_PLUGIN="$VDOT/plugins/tmux-plugin"
export CD_COUNT="0"
fi

include $VLIBS/lib.shell

if [ "$EXP" -eq 1 ]; then
# add path #
add_path "$VLIBS"
add_path "$HOME/.local/bin"
[ -d "$VUSER" ] && add_path "$VUSER/bin"

# rm path #
clean_path "/usr/games"
clean_path "/usr/local/games"

# FZF
if [ -n "$(which fzf)" ]; then
    export FZF_DEFAULT_COMMAND='ag -g ""'
    export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"
fi

if [ -d "$HOME/.local/usr/local/lib/pkgconfig" ]; then
    export PKG_CONFIG_PATH=$HOME/.local/usr/local/lib/pkgconfig
fi

fi
### EXPORT ONCE END

### set current shell
shopt -s expand_aliases

# append to the history file, don't overwrite it
shopt -s histappend # 用户打开多个终端（产生多个session）情况下，共享history

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
# shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
# [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# tput init
[ -x /usr/bin/tput ] && PS1='\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\]\[\033[01;36m\]$([ "$SHLVL" -ne 1 ] && echo \ $SHLVL)\[\033[00m\] \$ '

for i in $(ls $VLIBS); do
    complete -F complete_for_lib $i
done

if [ -d "$VUSER" ]; then
    (lib.misc check_ln)
    [ -f "$VUSER/init" ] && include "$VUSER/init load"
fi

# echo 'clean history' | at now > /dev/null 2>&1
include $VINIS/ini.shell

if [ -n "$(which dircolors)" ]; then
	eval $(dircolors -b "$VGL_DATA"/dir_colors)
fi

if shopt -q progcomp && [ -r /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
fi

for i in $(LC_ALL=C command ls "$HOME/.bin/data/completions"); do
    i=$HOME/.bin/data/completions/$i
    [[ -f $i && -r $i ]] && . "$i"
done

stty -ixon

unset EXP

echo init done
