#!/bin/bash

os="ubuntu"
# host="local"
host="server"
# sudo="y"


# ubuntu初安装

# 分区方法：
# /     30G~50G左右  ext4 主分区
# swap  物理内存两倍 swap 逻辑分区
# /boot 10G          ext4 逻辑分区
# /home 剩下的       ext4 逻辑分区
#-------------------------------------------------#

if [ $host == "local" ]; then
    # manual wlan
    # manual shell-extensions store
    tar -cf  extensions.tar.gz -C ~/.local/share/gnome-shell
fi

if [ $sudo == "y" ]; then
    # change sources.list
    sudo mv -i /etc/apt/sources.list /etc/apt/sources.list.bak

    sudo echo "
    deb http://mirrors.aliyun.com/ubuntu/ focal main restricted universe multiverse
    deb http://mirrors.aliyun.com/ubuntu/ focal-security main restricted universe multiverse
    deb http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted universe multiverse
    deb http://mirrors.aliyun.com/ubuntu/ focal-proposed main restricted universe multiverse
    deb http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ focal main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ focal-security main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ focal-proposed main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse
    " > /etc/apt/sources.list

    sudo apt update
    # apt upgrade
    sudo apt install aptitude

    function ins() {
        pro=$1
        # dpkg -l $pro > /dev/null
        # [ $? -eq 0 ] && return
        aptitude install $pro
    }

fi

## manual
## bug
## set ip
# lan="eno1"
# ifconfig eth0 down
# ifconfig $lan 192.168.3.89 # 给eth0网卡配置IP地址
# route add default gw 192.168.3.1
# gnome-control-center
# echo set dns to 192.168.1.2
# ifconfig eth0 up

# setting manual

# 必装
if [ $sudo == "y" ]; then

    if [ $host == "local" ]; then
        ins timeshift
        ins adb
        ins minicom
        # ins icaclient
        ins cifs-utils # for mount win dir!!!
    # ins gnome-tweaks
    # ins gnome-shell-extensions
    fi
    # ins gdebi-core
    # ins openssh-server
    # ins net-tools
    # ins sshfs
    # ins solaar
    # ins git
    # ins fzf
    # ins xclip
    # ins silversearcher-ag
    # ins aria2
    # ins ccls
    # ins npm
    # sudo npm install yarn -g
    # npm config set registry https://registry.npm.taobao.org/
    # yarn config set registry https://registry.npm.taobao.org/
    # ins python3-pip
    pip config set global.index-url 'https://pypi.tuna.tsinghua.edu.cn/simple'
    pip config set install.trusted-host 'mirrors.aliyun.com'

# sudo pip3 install neovim
# ins ninja-build
fi

# manual 输入法 
# manual mail
# ins thunderbird
# gdebi wps-office_11.1.0.9126_amd64.deb

## vim
# ins libpython2.7
# ins libpython2.7-dev
# ins libpython3.8-dev
#-------------------------------------------------#
# You need to install a terminal library:
apt-get install libncurses5-dev
# ins libncurses5-dev # for vim
# Python.h: No such file or directory:
apt-get install python2.7-dev
#-------------------------------------------------#
# cd /tmp/mnt/3.3/.local/tools/vim && ./a.sh
# ins gawk

# 7yuv
# ins nodejs
# sudo npm install -g n # 安装用于安装nodejs的模块n
# sudo n stable # 通过n模块安装指定的nodejs

# typora:
# wget -qO - https://typora.io/linux/public-key.asc | apt-key add -
# add-apt-repository 'deb https://typora.io/linux ./'
# apt-get update
# ins typora

# ins build-essential

# nautilus-image-converter

# ins python3.8
# ins libusb-1.0.0-dev
# ins xdotool
# ins gitk
# ins meld
# ins make
# ins cmake
# ins libtool-bin
# ins autoconf
# ins rdfind
# ins go

# go切换proxy中国代理
# GO111MODULE
# GO111MODULE 有三个值：off, on和auto（默认值）。

# GO111MODULE=off，go命令行将不会支持module功能，寻找依赖包的方式将会沿用旧版本那种通过vendor目录或者GOPATH模式来查找。
# GO111MODULE=on，go命令行会使用modules，而一点也不会去GOPATH目录下查找。
# GO111MODULE=auto，默认值，go命令行将会根据当前目录来决定是否启用module功能。这种情况下可以分为两种情形：
# 当前目录在GOPATH/src之外且该目录包含go.mod文件
# 当前文件在包含go.mod文件的目录下面。

# go:
# go env -w GO111MODULE=on
# go env -w GOPROXY=https://goproxy.io
# 注： https://goproxy.io 也可替换成阿里云的 https://mirrors.aliyun.com/goproxy或https://goproxy.cn,direct


# 输入法
# fcitx
# gdebi sogoupinyin_2.2.0.0108_amd64.deb
# rm fcitx-qimpanel
# libfcitx-qt5-1
# 配置 快捷键

# libwebkit-1.0-2

# numlockx
# vi /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
# add "greeter-setup-script=/usr/bin/numlockx on"

# /* win */
# font
# ssh-keygen
# add sshkey
# ssh-keygen -t rsa

# tar cvpzf 4.152-bak.tgz --exclude=/tmp --exclude=/proc --exclude=/lost+found/ --exclude=/sys --exclude=/mnt --exclude=/media --exclude=/dev --exclude=/var /
# mkdir -p tmp proc lost+found sys mnt media dev var

# gsettings set org.gnome.settings-daemon.plugins.power button-power suspend

# iptux

# 添加32位体系结构支持：
# dpkg --add-architecture i386


# 有待添加
# route to rc.local

# user@ingenic /etc $ route -F
# Kernel IP routing table
# Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
# default         bogon           0.0.0.0         UG    600    0        0 wlp0s20f3
# default         localhost       0.0.0.0         UG    20100  0        0 eno1
# 10.4.20.0       0.0.0.0         255.255.255.0   U     600    0        0 wlp0s20f3
# link-local      0.0.0.0         255.255.0.0     U     1000   0        0 wlp0s20f3
# 192.168.3.0     0.0.0.0         255.255.255.0   U     100    0        0 eno1


# ln -sf /tmp/mnt/3.3/work/local_debug
# ln -sf /tmp/mnt

python先不要安装新版了，只要2 3都有就行，主要是扩展包。
apt-get install autoconf
apt-get install automake
apt-get install pkg-config
apt-get install libgtk-3-dev

# 系统精简：
# 卸载libreOffice，选择用WPS来替代：
# apt-get remove libreoffice-common

apt-get remove thunderbird totem rhythmbox empathy brasero simple-scan gnome-mahjongg aisleriot gnome-mines cheese transmission-common gnome-orca webbrowser-app gnome-sudoku landscape-client-ui-install onboard deja-dup 
#-------------------------------------------------#
apt-get install安装目录是包的维护者确定的，不是用户

### vsudoer
add vsudoer to /etc/sudoers use sudo visudo
sed -i '/%sudo/c %sudo  ALL=(ALL:ALL)  NOPASSWD:ALL' /etc/sudoers
visudo -c#检查语法是否正确，一定要执行，否则出现问题很麻烦

# smartmontools nvme test
### backup
# bak cp -r ~/.local/share/gnome-shell/extensions/

